---
all:
  children:
    molecule:
      hosts:
        instance:
          ansible_connection: containers.podman.podman
          container_image: "docker.io/xiple/docker-{{ lookup('env', 'MOLECULE_DISTRO') | default('fedora42', true) }}-ansible:latest"
          container_command: sleep 1d
          container_privileged: false
          container_rm: true
          container_rmi: false
