---
- name: Verify
  hosts: molecule
  gather_facts: true
  vars_files:
    - ../../vars/main.yml
  tasks:
    - name: Get information on vscode repo file
      ansible.builtin.stat:
        path: /etc/yum.repos.d/vscode.repo
      register: vscode_repo_file

    - name: Fail if vscode repo file does not exist
      ansible.builtin.fail:
        msg: "/etc/yum.repos.d/vscode.repo file does not exist"
      when: not vscode_repo_file.stat.exists

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Fail if 'code' package is not installed
      ansible.builtin.fail:
        msg: "code package is not installed"
      when: "'code' not in ansible_facts.packages"
