---
- name: Verify
  hosts: molecule
  vars_files: ../../vars/main.yml
  gather_facts: true
  tasks:
    - name: Get information on vscode repo file
      ansible.builtin.stat:
        path: "{{ vscode_yum_repo_file_dest }}"
      register: vscode_repo_file

    - name: Fail if vscode repo file does not exist
      ansible.builtin.fail:
        msg: "{{ vscode_yum_repo_file_dest }} file does not exist"
      when: not vscode_repo_file.stat.exists

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Fail if 'code' package is not installed
      ansible.builtin.fail:
        msg: "code package is not installed"
      when: "'code' not in ansible_facts.packages"
